version: '3'
services:
  postgres:
    image: postgres
    container_name: iw_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/var/lib/postgresql/data/log

#  flask:
#    build:
#      context: ./
#      dockerfile: deploy/Dockerfile_app
#    image: flask_img
#    container_name: flask
#    volumes:
#      - ./app/data/:/app/data
#
#    ports:
#      - "80:80"
#    command: /usr/bin/supervisord
